//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Carts = new HashSet<Cart>();
            this.Orders = new HashSet<Order>();
            this.ProductMetas = new HashSet<ProductMeta>();
        }
    
        public long Id { get; set; }
        public Nullable<int> Inventory_Id { get; set; }
        public string Title { get; set; }
        public string Title_ar { get; set; }
        public string Meta_Title { get; set; }
        public string Slug { get; set; }
        public string Summary { get; set; }
        public string Summary_ar { get; set; }
        public Nullable<int> Type { get; set; }
        public string SKU { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> Disount_ID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<byte> Shop { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
        public Nullable<System.DateTime> PublishedAt { get; set; }
        public Nullable<System.DateTime> StartsAt { get; set; }
        public Nullable<System.DateTime> EndsAt { get; set; }
        public string Details { get; set; }
        public string Details_ar { get; set; }
        public Nullable<int> Category_ID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cart> Carts { get; set; }
        public virtual Category Category { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual Inventory Inventory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMeta> ProductMetas { get; set; }
    }
}
